### ISSUE TITLE
Cross-correlation of  zc sequence and samples looks error

### ISSUE THREAD

**Issue by jianjianliu0918** [proto17/dji_droneid#12]
Hello everyone
I tried run the uav iq data in code matlab/updated_scripts/process_file.m.
The cross-correlation of  zc sequence and samples looks wrong. The results dosen't have a good correlation peak.
The relevant parameters are as follows:
Data record board: usrp b210, sample rate 30.72MHz
UAV type: DJI AIR2, transmission system is DJI OCUSYNC 2.0.

edit the matlab code as follows:
file_sample_rate = 30.72e6;
chunk_size = 10e6;

Waterfalls:
![stft](https://user-images.githubusercontent.com/42163077/184865228-607142fe-a32a-4226-9644-9b5b5c1b9a79.jpg)

Spetrum:
![air2_spetrum](https://user-images.githubusercontent.com/42163077/184865287-303055b8-5c36-460c-b3f0-1555134192fc.jpg)

Result of cross correlation:
![air2_corr](https://user-images.githubusercontent.com/42163077/184865367-782bf70f-3b2c-4967-aa85-b2cb209d541c.jpg)

**Comment by proto17** [comment]
The number of frames you are seeing makes me believe that you are looking at the downlink signal and not the DroneID signal.  The DroneID signal is not nearly that active.  I don't recall exactly, but I think it's something like every 600 milliseconds.  The downlink signal can have the same bandwidth, but does not have the same structure, and likely doesn't use the same ZC sequences.  Initially I thought you might be seeing the uplink, but I'm pretty sure that the uplink is ~ 1.5 MHz wide, where the downlink is selectable to something like 10 or 20 MHz.

**Comment by jianjianliu0918** [comment]
> The number of frames you are seeing makes me believe that you are looking at the downlink signal and not the DroneID signal. The DroneID signal is not nearly that active. I don't recall exactly, but I think it's something like every 600 milliseconds. The downlink signal can have the same bandwidth, but does not have the same structure, and likely doesn't use the same ZC sequences. Initially I thought you might be seeing the uplink, but I'm pretty sure that the uplink is ~ 1.5 MHz wide, where the downlink is selectable to something like 10 or 20 MHz.

Yes, I analyzed the downlink drones video transmitter signal above, it seems that I have misunderstood, Tomorrow I will re-analyze the uplink signal.
Thanks!

**Comment by proto17** [comment]
The uplink will not work with this code either.  This code only supports DroneID which comes from the drone, not the controller.  There is a list [1] of frequencies that are known to carry DroneID signals for reference.  The bursts that you see should be very infrequent, only stay on the same frequency for ~ 20-30 bursts, and hop around quite a bit.

[1] https://github.com/proto17/dji_droneid#frequencies

**Comment by jianjianliu0918** [comment]
> The uplink will not work with this code either. This code only supports DroneID which comes from the drone, not the controller. There is a list [1] of frequencies that are known to carry DroneID signals for reference. The bursts that you see should be very infrequent, only stay on the same frequency for ~ 20-30 bursts, and hop around quite a bit.
> 
> [1] https://github.com/proto17/dji_droneid#frequencies

I have record data as a frequency list, and found a strong corrleation with zc seq.

DJI Mavic 3,  central frequnce is 2445.5MHz:
cross correlation results (I don't know why this result are not normalized, so I set the thresold to 14):
![norm_xcorr](https://user-images.githubusercontent.com/42163077/185056366-b5ef5d39-8ba1-4662-8195-8b394b9f8b76.jpg)

corresponding position：
![zc_found_2445 5](https://user-images.githubusercontent.com/42163077/185055196-67086feb-aadf-4bee-b86f-ae31b2cdd0e7.png)

Then I calculate the correlation between the extracted CP and OFDM frame structure data，and the result doesn't seem to be correct. Normally, this results should have multiple peaks associated with the CP position.
![cp_xcorr](https://user-images.githubusercontent.com/42163077/185061137-fffaf795-4bf0-4589-9e6a-d86e531ed61d.jpg)

Unsurprisingly,  the constellation results show that the signal demodulation process has errors.
![constell_result](https://user-images.githubusercontent.com/42163077/185061888-b34dc9c8-710a-4806-934d-e970efb0b637.jpg)

I don't know if there is a difference between  ocusync2.0 and ocusync3.0(Mavic 3). Or something went wrong in signal processing.

**Comment by jianjianliu0918** [comment]
An interesting phenomenon, I intercepted this signal, and then used the ofdm blind detection method to detect the CP position. 
Results show as follows:
![time_domain_cp_detection](https://user-images.githubusercontent.com/42163077/185109728-3b25f01e-3f88-4eeb-b74b-77b8bd2bb380.jpg)
Similar to ocusync 2.0 , two OFDM signals are also placed in front of the ZC sequence.
The entire signal has 8 cyclic prefixes (including the ZC seq).
These results make me suspect that this signal is the drone id signal for ocusync 3.0.

**Comment by proto17** [comment]
The MATLAB code in the `main` branch does use a normalized cross correlation to find the ZC sequence.  If you're using the MATLAB code from the GNU Radio branches then that might explain what you're seeing.  

The DroneID signal will either contain 9 or 8 OFDM symbols.  I have a Mini 2 that sends 9 symbols, but most of what I have seen from other collects is 8.  The code in this repo assumes that all 9 are there, but only actually does anything with the last 8.  

I don't currently do blind estimation using the cyclic prefix just because I have the ZC sequence which gives me a pretty accurate starting point as opposed to the very rough start index of the cyclic prefixes.  I do (in one version of the code somewhere) use the cyclic prefixes for coarse frequency offset estimation though.

My advice is to try the latest `main` branch of the repo and see if that helps with the correlation and ultimate data carrier extraction.

**Comment by jianjianliu0918** [comment]
> 



> The MATLAB code in the `main` branch does use a normalized cross correlation to find the ZC sequence. If you're using the MATLAB code from the GNU Radio branches then that might explain what you're seeing.
> 
> The DroneID signal will either contain 9 or 8 OFDM symbols. I have a Mini 2 that sends 9 symbols, but most of what I have seen from other collects is 8. The code in this repo assumes that all 9 are there, but only actually does anything with the last 8.
> 
> I don't currently do blind estimation using the cyclic prefix just because I have the ZC sequence which gives me a pretty accurate starting point as opposed to the very rough start index of the cyclic prefixes. I do (in one version of the code somewhere) use the cyclic prefixes for coarse frequency offset estimation though.
> 
> My advice is to try the latest `main` branch of the repo and see if that helps with the correlation and ultimate data carrier extraction.
> 
> EDIT:
> 
> For reference, see [1] which is where the normalized cross correlation function is called. In previous versions the correlation was done with the `filt` function. This did not produce normalized results, so it was changed to `xcorr(x, y, 0, 'normalized')` but that function is _very_ slow in MATLAB and unusable in Octave. So a custom function was written that is probably closer to an approximation of the normalized correlation, but seems to work pretty well.
> 
> [1] https://github.com/proto17/dji_droneid/blob/main/matlab/updated_scripts/find_zc_indices_by_file.m#L118

I tried to use the latest main branch, and used dji air2 droen. Finally, I got a good demodulation effect.
![image](https://user-images.githubusercontent.com/42163077/185534446-b2625190-e319-40f2-b503-cefabab17d52.png)
After,I get the demodulated frame sequence，which consists of 352 characters.  It looks different from the sequence composition in function **create_frame_bytes**. 
It would be great if you could give me some help with frame seq decode.

**Comment by proto17** [comment]
Congrats on the demod!  The bytes you are seeing are *all* of the bytes that were demodulated.  The frame length depends on the frame type that was sent by the drone.  To avoid potentially clipping bits that are important, I provide the user with all of the bytes that were demodulated.  If you just want the bytes that matter, change the loop at [1] to use `payload_length` instead of `decoded_bytes.size()`

**Comment by jianjianliu0918** [comment]
> Congrats on the demod! The bytes you are seeing are _all_ of the bytes that were demodulated. The frame length depends on the frame type that was sent by the drone. To avoid potentially clipping bits that are important, I provide the user with all of the bytes that were demodulated. If you just want the bytes that matter, change the loop at [1] to use `payload_length` instead of `decoded_bytes.size()`
> 
> [1] https://github.com/proto17/dji_droneid/blob/main/cpp/remove_turbo.cc#L168
Valid! The demodulated sequence can correspond to the fram structure! In addition, I also demodulated the DJI mavic3 drone ID signal, the method proposed by this repo is also effective. 
Impressive work, thanks again for your reply!
