### ISSUE TITLE
zc_start + 6

### ISSUE THREAD

**Issue by maurokenny** [proto17/dji_droneid#13]
Hi,

on the commit `a731a12660eb10d352d944287b49cddf6cee2b31` a new line
`zc_start = zc_start + 6;` (line 196, file process_file.m) was added.

I was expecting the previous line `zc_start = long_cp_len + (fft_size * 3) + (short_cp_len * 3);` to be enough.
Would you mind explaining why this line was added?

Thanks

**Comment by proto17** [comment]
You're 100% right.  I had that in place while testing the `skip` variable just below that line.  It should have been removed.  Thanks for pointing it out!
