### ISSUE TITLE
normalized_xcorr_fast undefined

### ISSUE THREAD

**Issue by lobart** [proto17/dji_droneid#17]
Hi!  @proto17 
I try follow manual https://github.com/proto17/dji_droneid/wiki/DJI-Mavic-3-DroneID-Analysis
But i cant find normalized_xcorr_fast.
May be you forget commit this file?

**Comment by proto17** [comment]
That file is found in https://github.com/proto17/dji_droneid/tree/main/matlab/updated_scripts.  Add that directory to your MATLAB/Octave path

**Comment by lobart** [comment]
Sorry, my mistake
