### ISSUE TITLE
cfo detection

### ISSUE THREAD

**Issue by catkira** [proto17/dji_droneid#23]
isnt in [this](https://github.com/proto17/dji_droneid/blob/main/matlab/updated_scripts/process_file.m#:~:text=offset_radians%20%3D%20angle(dot(cyclic_prefix%2C%20symbol_tail))%20/%20fft_size%3B) line the conjugate needed?
```m  
    offset_radians = angle(dot(cyclic_prefix, symbol_tail)) / fft_size;
```
like
```m  
    offset_radians = angle(dot(cyclic_prefix, conj(symbol_tail))) / fft_size;
```

**Comment by oyd11** [comment]
No, the second argument in a complex dot project, is already conj() by definition AFAIK

**Comment by oyd11** [comment]
yes, this is always slightly confusion between libraries, btw: note that `np.vdot()` does the `conj()`, where indeed `np.dot()` does not.
