### ISSUE TITLE
Compiled version of the "add_turbo.cc" and "remove_turbo.cc"

### ISSUE THREAD

**Issue by Retinaaa** [proto17/dji_droneid#5]
I'm excited about dji_droneid. I have a USRP B200. Furthermore, I want to test the DroneID burst using these codes.
But I work with Matlab in windows. Accordingly, Please send the Compiled Windows version of the "add_turbo.cc" and "remove_turbo.cc"?
Thanks a lot :smiley:

**Comment by proto17** [comment]
Unfortunately I don't know enough about Windows to know how to compile the turbofec library for Windows and then link it with my encode/decode apps :(  Perhaps CYGWIN would work for this?  Or maybe there is a way to have VisualStudio import a Linux Makefile and translate it?

**Comment by proto17** [comment]
Good point!  Supposedly WSL2 supports X11 apps [1].  You could install MATLAB in WSL (assuming you have enough licenses remaining) and run MATLAB from there.  I haven't personally tried using WSL for MATLAB work, so I can't promise it will work.

Also, for native Windows, when we are able to get a .exe created, the `process_file.m` script will need to be updated [2] to have a `.exe` extension.  I'm not sure about any additional DLL path requirements once built into an EXE.

[1] https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
[2] https://github.com/proto17/dji_droneid/blob/main/matlab/updated_scripts/process_file.m#L23

**Comment by alphafox02** [comment]
If you’re willing to try Linux, this ISO can be ran live and has been tested with a b205mini. It has all the code to include compiled tools mentioned above and a python3 based tool that converts the extract frame to human readable - all sitting in /usr/src/dji_droneid. While it doesn’t help with windows, It’s there if you need it. 
https://sourceforge.net/projects/dragonos-focal/files/

**Comment by Retinaaa** [comment]
Thanks a lot, I need instructions on how to build the binary and dependencies?

**Comment by Retinaaa** [comment]
do:
1)Install Linux on Windows with WSL
2)Download Ubuntu
3)Configure Ubuntu
4)Install and use a GUI package(octave)
5)execute 
https://github.com/proto17/dji_droneid/tree/main/matlab/updated_scripts/transmit
6) Pic
![image](https://user-images.githubusercontent.com/106088840/170479488-836651fc-ae23-4230-a515-a3ae0a9af188.png)

**Comment by Retinaaa** [comment]
plz help, I need instructions on how to build the binary and dependencies of "turbo.cc"?

**Comment by proto17** [comment]
Have a look at the top of either `.cc` file and you should see instructions on exactly what command to run to build the binary [1] [2]

To install `libturbofec` see [3]

[1] https://github.com/proto17/dji_droneid/blob/main/cpp/add_turbo.cc#L1-L7
[2] https://github.com/proto17/dji_droneid/blob/main/cpp/remove_turbo.cc#L1-L7
[3] https://github.com/ttsou/turbofec#compile

**Comment by MAVProxyUser** [comment]
@Retinaaa  better steps 
1) use DragonOS... all is already premade for you. https://sourceforge.net/projects/dragonos-focal/files/
2) profit.

**Comment by Retinaaa** [comment]
@MAVProxyUser 
@proto17 
@alphafox02 
Successfully compiled
Thanks for your good guidance ;)
