### ISSUE TITLE
Fast correlation

### ISSUE THREAD

**Issue by karatemir** [proto17/dji_droneid#7]
In `README` you mention:

> A normalized autocorrelation would likely be as slow as the cross correlation, which probably rules out autocorrelating for the ZC sequence. I'd love to hear some ideas to help speed this process up.

If you have access to a decent GPU, it might be worth giving CuPy and [CuSignal](https://developer.nvidia.com/blog/accelerated-signal-processing-with-cusignal/) a shot.

**Comment by proto17** [comment]
Appreciate the tip, and you're def not wrong that GPUs can do this kinda thing a lot better than CPUs.

But, MATLAB is where development work on signal processing chains happens in a lot of cases.  To the best of my knowledge there isn't a simple way for me to make my MATLAB simulations magically run on a GPU.  So, specific to simulation and testing work, I'm stuck on a CPU which does take quite a while with a tool like MATLAB.  Just the price you pay for convenience and accuracy =\

Thanks!
